services:
  zap:
    image: zaproxy/zap-stable
    container_name: callme_yoghurt_zap
    ports:
      - "8080:8080"
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true -config api.addrs.any=true
    volumes:
      - zap_data:/home/zap/.ZAP
    restart: "no"

volumes:
  zap_data:
